insert into productos (nombre, descripcion, precio, cantidad, imagen_url)values('Galletas Muuu','Deliciosas Galletas',100, 50, 'assets/productos/producto1.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url)values('Jabon Axion','Muy bueno pa la grasa',1000, 50, 'assets/productos/producto2.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url)values('Aceite Premier','Descripcion simple',6008, 50, 'assets/productos/producto3.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Arroz Diana', 'Descripcion simple', 200, 50, 'assets/productos/producto4.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Frijol El Trece', 'Descripcion simple', 300, 50, 'assets/productos/producto5.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Pastas Doria', 'Descripcion simple', 400, 50, 'assets/productos/producto6.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Pan Fresco', 'Descripcion simple', 500, 50, 'assets/productos/producto7.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Carne Molida Cerdo', 'Descripcion simple', 600, 50, 'assets/productos/producto8.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Manzana', 'Descripcion simple', 700, 50, 'assets/productos/producto9.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Queso DobleCrema', 'Descripcion simple', 800, 50, 'assets/productos/producto10.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Pechuga de Pollo', 'Descripcion simple', 900, 50, 'assets/productos/producto11.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Papel Higienico Scott', 'Descripcion simple', 1000, 50, 'assets/productos/producto12.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Detergente Liquido', 'Descripcion simple', 1100, 50, 'assets/productos/producto13.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Crema Colgate', 'Descripcion simple', 1200, 50, 'assets/productos/producto14.jpg')
insert into productos (nombre, descripcion, precio, cantidad, imagen_url) values ('Bananos', 'Descripcion simple', 1300, 50, 'assets/productos/producto15.jpg')

